server:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - monitoring.example.com
    extraPaths: []
    - path: /
      backend:
        service:
            name: prometheus-server
            port:
              number: 80
alertmanager:
  enabled: true
nodeExporter:
  enabled: true
pushgateway:
  enabled: true
kubeStateMetrics:
  enabled: true