apiVersion: v1
kind: Service
metadata:
  name: {{ include "kutt.fullname" . }}-postgres
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: {{ include "kutt.fullname" . }}-postgres
