apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kutt.fullname" . }}-redis
spec:
  selector:
    matchLabels:
      app: {{ include "kutt.fullname" . }}-redis
  serviceName: "redis"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: {{ include "kutt.fullname" . }}-redis
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis
          mountPath: /data
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: {{ include "kutt.fullname" . }}-redis