apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kutt.fullname" . }}
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
data:
  DB_USER: {{ default "" .Values.postgres.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ default "" .Values.postgres.dbPassword | b64enc | quote }}
  DB_NAME: {{ default "" .Values.postgres.dbName | b64enc | quote }}